#!/usr/bin/env perl

# This file is part of Command and Data Handeling Git Hooks.
#
# Command and Data Handeling Git Hooks is free software: you can
# redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation, either
# version 3 of the License, or (at your option) any later version.
#
# Command and Data Handeling Git Hooks is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with CDH test assignmen.  If not, see <http://www.gnu.org/licenses/>.

use Data::Dumper;

use strict;
use warnings;

my $install_directory = "./.git/hooks/";
my $shellrc = ".bashrc";

foreach my $arg (@ARGV) {
    if ($arg =~ /^--install-directory=(.*)/) {
        $install_directory = "$1";
    }
    elsif ($arg =~ /^--shell-config-file=(.*)/) {
        $shellrc = "$1";
    }
}

system("cp ~/bin/hooks/* $install_directory");
