#!/usr/bin/env perl
use Data::Dumper;

use strict;
use warnings;

my $install_directory = "./.git/hooks/";
my $shellrc = ".bashrc";

foreach my $arg (@ARGV) {
    if ($arg =~ /^--install-directory=(.*)/) {
        $install_directory = "$1";
    }
    elsif ($arg =~ /^--shell-config-file=(.*)/) {
        $shellrc = "$1";
    }
}

system("cp ~/bin/hooks/* $install_directory");
