#!/usr/bin/env perl

# This file is part of Command and Data Handeling Git Hooks.
#
# Command and Data Handeling Git Hooks is free software: you can
# redistribute it and/or modify it under the terms of the GNU General
# Public License as published by the Free Software Foundation, either
# version 3 of the License, or (at your option) any later version.
#
# Command and Data Handeling Git Hooks is distributed in the hope that it
# will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with CDH test assignmen.  If not, see <http://www.gnu.org/licenses/>.

use Data::Dumper;
use strict;
use warnings;

system('powerlint');

my $encountered_error = 0;
my @errors;

my $filename = 'output.dat';
open(my $fh, '<:encoding(UTF-8)', $filename)
  or die "Could not open file '$filename' $!";

while (my $row = <$fh>) {
  chomp $row;
  if (!($row =~ /^(?:Done|Total)|#ifndef header guard has wrong style|#endif line should be/)) {
   push(@errors, $row);
  }
}

if(@errors) {
  my $error;
  print("YOUR CODE CONTAINS LINTING ERRORS:\n\n");
  print Dumper (\@errors);
  print("\nPlease fix these errors befor resubmitting your code\nUse 'cat output.dat' for more info\n");
  exit (1);
} else {
  system('rm output.dat');
}
