#!/usr/bin/env perl
use Data::Dumper;
use strict;
use warnings;

system('powerlint');

my $encountered_error = 0;
my @errors;

my $filename = 'output.dat';
open(my $fh, '<:encoding(UTF-8)', $filename)
  or die "Could not open file '$filename' $!";

while (my $row = <$fh>) {
  chomp $row;
  if (!($row =~ /^(?:Done|Total)|#ifndef header guard has wrong style|#endif line should be/)) {
   push(@errors, $row);
  }
}

if(@errors) {
  my $error;
  print("YOUR CODE CONTAINS LINTING ERRORS:\n\n");
  print Dumper (\@errors);
  print("\nPlease fix these errors befor resubmitting your code\nUse 'cat output.dat' for more info\n");
  exit (1);
} else {
  system('rm output.dat');
}
